### ISSUE TITLE
[0.11-M1] Crashing with large flows

### ISSUE THREAD

**Issue by gzoller** [akka/reactive-kafka#129]
I'm seeing a crash with large flows.  My consume code is given here:

    count = 0
    val consumerSettings = ConsumerSettings(as, new ByteArrayDeserializer, new StringDeserializer, Set("lowercaseStrings"))
      .withBootstrapServers("192.168.99.100:9092")
      .withGroupId("group1")
      .withProperty(ConsumerConfig.AUTO_OFFSET_RESET_CONFIG, "earliest")

    val graph = RunnableGraph.fromGraph(GraphDSL.create() { implicit builder: GraphDSL.Builder[akka.NotUsed] =>
      import GraphDSL.Implicits._
      type In = CommittableMessage[Array[Byte],String]
      val src = Consumer.committableSource(consumerSettings.withClientId("client1"))  
      val commit = Flow[In].map{ msg => msg.committableOffset.commit()  }
      val show = Flow[In].map{ i => 
        count += 1
        if(i.value=="done") println(s"Time ($count): "+(System.currentTimeMillis() - now))
        i 
      }

      src ~> show ~> commit ~> Sink.ignore
      ClosedShape
    })
    now = System.currentTimeMillis()
    graph.run()

I restart Kafka each run so there's no left-over messages/offsets from previous run.
I pre-populate a single topic with just one partition for each run with some number of messages (Strings).
If I run this for a smaller number of messages pre-populated, maybe up to 10000, it works fine.
If I run it with 100,000 I get this error:

```
[ReactiveKafka-akka.kafka.default-dispatcher-11] ERROR akka.kafka.internal.CommittableConsumerStage$$anon$1 - Error in poll
java.lang.IllegalArgumentException: requirement failed
	at scala.Predef$.require(Predef.scala:207)
	at akka.kafka.internal.ConsumerStageLogic.handleResult$1(ConsumerStage.scala:372)
	at akka.kafka.internal.ConsumerStageLogic.poll(ConsumerStage.scala:384)
	at akka.kafka.internal.CommittableConsumerStage$$anon$1.poll(ConsumerStage.scala:145)
	at akka.kafka.internal.CommittableConsumerStage$$anon$1.commitAsync(ConsumerStage.scala:257)
	at akka.kafka.internal.CommittableConsumerStage$$anon$1.akka$kafka$internal$CommittableConsumerStage$$anon$$commitSingleInternal(ConsumerStage.scala:223)
	at akka.kafka.internal.CommittableConsumerStage$$anon$1$$anonfun$6.apply(ConsumerStage.scala:131)
	at akka.kafka.internal.CommittableConsumerStage$$anon$1$$anonfun$6.apply(ConsumerStage.scala:130)
	at akka.stream.impl.fusing.GraphInterpreter.runAsyncInput(GraphInterpreter.scala:569)
	at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:417)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:593)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:604)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:482)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:519)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by patriknw** [comment]
thanks

**Comment by l15k4** [comment]
Hey, I get this error too on flow with 10 elements, it doesn't happen always though, it's sort of non-deterministic... Repro : 

```
import akka.kafka.scaladsl.{Consumer, Producer}
import akka.kafka.{ConsumerSettings, ProducerSettings}
import akka.stream.scaladsl.{Sink, Source}
import net.manub.embeddedkafka.{EmbeddedKafka, EmbeddedKafkaConfig}
import org.apache.kafka.clients.consumer.ConsumerConfig
import org.apache.kafka.clients.producer.ProducerRecord
import org.apache.kafka.common.serialization.{ByteArrayDeserializer, ByteArraySerializer, StringDeserializer, StringSerializer}
import org.scalatest.time.{Second, Seconds, Span}

class KafkaPlayground extends AkkaSuite {
  implicit val futurePatience = PatienceConfig(timeout = Span(30, Seconds), interval = Span(1, Second))
  implicit val config = EmbeddedKafkaConfig(kafkaPort = 9092, zooKeeperPort = 2181)

  override def beforeAll(): Unit = try super.beforeAll() finally {
    EmbeddedKafka.start()
  }
  override def afterAll(): Unit = try super.afterAll() finally {
    EmbeddedKafka.stop()
  }

  "foo" in {

    val producerSettings =
      ProducerSettings(system, new ByteArraySerializer, new StringSerializer)
        .withBootstrapServers("localhost:9092")

    def consumerSettings(topic: String, clientId: String) =
      ConsumerSettings(system, new ByteArrayDeserializer, new StringDeserializer, Set(topic))
        .withBootstrapServers("localhost:9092")
        .withClientId(clientId)
        .withGroupId("group1")
        .withProperty(ConsumerConfig.AUTO_OFFSET_RESET_CONFIG, "earliest")

    // publish events from topic1 to topic2
    Consumer.committableSource(consumerSettings("topic1", "client1"))
      .map { msg =>
        Producer.Message(new ProducerRecord[Array[Byte], String]("topic2", msg.value), msg.committableOffset)
      }.to(Producer.commitableSink(producerSettings)).run()

    val sf = Consumer.atMostOnceSource(consumerSettings("topic2", "client1"))
      .take(10)
      .map { record =>
        record
      }.runWith(Sink.seq)

    Source(1 to 10)
      .map(_.toString)
      .map { elem =>
        new ProducerRecord[Array[Byte], String]("topic1", elem)
      }.runWith(Producer.plainSink(producerSettings))

    whenReady(sf) { result =>
      println(result)
    }
  }
}
```

**Comment by l15k4** [comment]
I just tested that with `0.11-SNAPSHOT` and it works! :+1:

**Comment by patriknw** [comment]
Thanks. I think I'll cut a new milestone at the end of the week
