### ISSUE TITLE
Source.actorPublisher does not recognize actors created using the ActorDSL

### ISSUE THREAD

**Issue by lapminglee** [akka/reactive-kafka#157]
When I use ActorDSL to create a stream, it doesn't recognize the actor

I am using SBT:  `"com.typesafe.akka" %% "akka-stream-kafka" % "0.11-M3"`

```
java.lang.IllegalArgumentException: requirement failed: Actor must be ActorPublisher
	at scala.Predef$.require(Predef.scala:224)
	at akka.stream.scaladsl.Source$.actorPublisher(Source.scala:352)
	at science.peers.server.metrics.actor.send.ProducerStream$.apply(ProducerStream.scala:17)
	at science.peers.server.metrics.akka.StreamSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(StreamSpec.scala:70)
	at science.peers.server.metrics.akka.StreamSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(StreamSpec.scala:39)
	at science.peers.server.metrics.akka.StreamSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(StreamSpec.scala:39)
	at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:953)
	at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
	at science.peers.server.metrics.akka.StreamSpec.withFixture(StreamSpec.scala:32)
	at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:950)
	at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
	at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
	at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:962)
	at science.peers.server.metrics.akka.StreamSpec.runTest(StreamSpec.scala:32)
	at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
	at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:390)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:427)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
	at org.scalatest.WordSpecLike$class.runTests(WordSpecLike.scala:1021)
	at science.peers.server.metrics.akka.StreamSpec.runTests(StreamSpec.scala:32)
	at org.scalatest.Suite$class.run(Suite.scala:1424)
	at science.peers.server.metrics.akka.StreamSpec.org$scalatest$WordSpecLike$$super$run(StreamSpec.scala:32)
	at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1067)
	at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1067)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:545)
	at org.scalatest.WordSpecLike$class.run(WordSpecLike.scala:1067)
	at science.peers.server.metrics.akka.StreamSpec.org$scalatest$BeforeAndAfterAll$$super$run(StreamSpec.scala:32)
	at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:257)
	at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:256)
	at science.peers.server.metrics.akka.StreamSpec.run(StreamSpec.scala:32)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:55)
	at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2563)
	at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2557)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:2557)
	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1044)
	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1043)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:2722)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1043)
	at org.scalatest.tools.Runner$.run(Runner.scala:883)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2(ScalaTestRunner.java:138)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:28)
```

```
        Source.actorPublisher(Props(new Act with ActorPublisher[ProducerRecord[Array[Byte], Array[Byte]]] {
          val out = new ByteArrayOutputStream()
          val queue = mutable.Queue.empty[ProducerRecord[Array[Byte], Array[Byte]]]

          become {
            case msg: ProducerMessage ⇒
              out.reset()
              val os = AvroOutputStream[ProducerMessage](out)
              os.write(msg)
              os.flush()
              os.close()
              queue enqueue new ProducerRecord(topicName, out.toByteArray)
              deliverMessage()

            case Request(_) ⇒ deliverMessage()
            case Cancel ⇒ context.stop(self)
          }

          def deliverMessage(): Unit = {
            while (isActive && totalDemand > 0 && queue.nonEmpty) {
              onNext(queue.dequeue())
            }
          }
        }))

**Comment by ktoso** [comment]
Thanks for reporting.

1) Please don't write Publishers. Really, they're VERY LOW LEVEL and you'll more likely than not get their implementation wrong. Please use `GraphStage` instead.
2) I'm not sure we care about ActorDSL that much to be honest... It hasn't been used by that many people in recent years.

**Comment by patriknw** [comment]
I think that can be written as a `Source.queue` followed by stateless `map` that performs the avro conversion. If it must be stateful you can use `statefulMapConcat`.
