### ISSUE TITLE
Using reactive kafka with other Reactive Stream APIs

### ISSUE THREAD

**Issue by ErunamoJAZZ** [akka/reactive-kafka#162]
Hello.

I want use _Slick Streams_ with _Reactive Kafka_, because I need "broadcast" some data. 

I made one consumer that consult in my DB a stream, and I flatten it, and tried to send  `ProducerRecord`. 
This is a example code:

### Slick (Publisher to Source)
```scala
case class Travel(id: Long, airportId: Int, ...)

//Actually, this is Slick code for stream data form Database
object MyDatabase{
  def streamAirline(airportId:Int): Source[Int, NotUsed] = {
    val q = AirportAirlineTable
      .filter(_.airportId === airportId)
      .map(_.airportId)

    val publisher = db.stream(q.distinct.sortBy(a => a).result)
    Source.fromPublisher(publisher)
  }
}
```

### Reactive Kafka:
```scala
// Creating Consumer and Producer (with configuration inside, etc)
val c = new MyKafkaConsumer[Travel](actorSystem)
val p = new MyKafkaProducer[Travel](actorSystem)

Consumer.committableSource(c.consumerSettings(Set("topic_travels_airport")).withGroupId("consumer1"))
  // here flat ((x,x,x,x),(y,y,y,y,y)) to (x,x,x,x,y,y,y,y,y), I think, or maybe im wrong?
  .flatMapConcat { msg =>
    val item = msg.value
    //get the new Source streamed form DB
    MyDatabase.streamAirline(item.airportId).map { airlineId =>
      ProducerMessage.Message(new ProducerRecord[KafkaKey, Travel](s"topic_airlines_$airlineId", item), msg.committableOffset)
    }
  }
  .to(Producer.commitableSink(p.settings))
```
This code compile, but does not execute. I have the next error:

### Error
```
[error] a.d.TaskInvocation - requirement failed: client id must be defined when using committable offsets
java.lang.IllegalArgumentException: requirement failed: client id must be defined when using committable offsets
	at scala.Predef$.require(Predef.scala:224)
	at akka.kafka.internal.CommittableConsumerStage.<init>(ConsumerStage.scala:122)
	at akka.kafka.scaladsl.Consumer$.committableSource(Consumer.scala:81)
	at utilities.kafkatestService$$anonfun$3.apply$mcV$sp(MyTestingKafka.scala:152)
	at akka.actor.Scheduler$$anon$4.run(Scheduler.scala:122)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:405)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
```

Actually, Im very new using Akka Streams and Kafka, so, I dont understand why this fail.

Thanks

**Comment by 13h3r** [comment]
Set client.id for performing commits. Call `withClientId` from `ConsumerSettings`

**Comment by ErunamoJAZZ** [comment]
Wow, yeah. I was wondered if that was more complicated, hehehe.

The error message could suggest use `withClientId()` explicitly, imo.

Thank you very much!!

**Comment by patriknw** [comment]
I think we are adjusting the settings api in upcoming version to make it clear what is mandatory.
