### ISSUE TITLE
Producing messages during broker restart throws UnknownTopicOrPartitionException

### ISSUE THREAD

**Issue by bfil** [akka/reactive-kafka#163]
I have a very simple producer that produces a message every second using the new API (0.11-M3):

```scala
val decider: Supervision.Decider = {
  case ex: Exception =>
    log.error(ex, ex.getMessage)
    Supervision.Resume
}

Source(1 to 100)
  .throttle(1, 1 second, 1, ThrottleMode.shaping)
  .map(_.toString)
  .map(elem => {
    log.info(s"Producing: test-$elem")
    ProducerMessage.Message(new ProducerRecord[Array[Byte], String](topic, s"test-$elem"), s"test-$elem")
  })
  .via(Producer.flow(producerSettings).withAttributes(ActorAttributes.supervisionStrategy(decider)))
  .map { result =>
    val record = result.message.record
    log.info(s"Produced message: ${record.value}, topic ${record.topic}, partition: ${record.partition}, offset: ${result.offset}")
    result
  }
  .runWith(Sink.ignore)
```

Messages are dropped and not published during a broker restart.
It seems to be caused by temporarily outdated client metadata because it fails to be fetched.

This is a sample of the logs I'm getting by using the above producer (messages 5 to 10 are lost):

```
[INFO] [2016-06-28 23:53:45.338] [akka.actor.ActorSystemImpl] Producing: test-1
[INFO] [2016-06-28 23:53:45.460] [akka.actor.ActorSystemImpl] Produced message: test-1, topic test, partition: null, offset: 29
[INFO] [2016-06-28 23:53:46.356] [akka.actor.ActorSystemImpl] Producing: test-2
[INFO] [2016-06-28 23:53:46.358] [akka.actor.ActorSystemImpl] Produced message: test-2, topic test, partition: null, offset: 30
[INFO] [2016-06-28 23:53:47.356] [akka.actor.ActorSystemImpl] Producing: test-3
[INFO] [2016-06-28 23:53:47.358] [akka.actor.ActorSystemImpl] Produced message: test-3, topic test, partition: null, offset: 31
[INFO] [2016-06-28 23:53:48.356] [akka.actor.ActorSystemImpl] Producing: test-4
[INFO] [2016-06-28 23:53:48.359] [akka.actor.ActorSystemImpl] Produced message: test-4, topic test, partition: null, offset: 32
[INFO] [2016-06-28 23:53:49.355] [akka.actor.ActorSystemImpl] Producing: test-5
[INFO] [2016-06-28 23:53:50.356] [akka.actor.ActorSystemImpl] Producing: test-6
[INFO] [2016-06-28 23:53:51.355] [akka.actor.ActorSystemImpl] Producing: test-7
[INFO] [2016-06-28 23:53:52.356] [akka.actor.ActorSystemImpl] Producing: test-8
[INFO] [2016-06-28 23:53:53.356] [akka.actor.ActorSystemImpl] Producing: test-9
[WARN] [2016-06-28 23:54:01.533] [o.apache.kafka.clients.NetworkClient] Error while fetching metadata with correlation id 6 : {test=LEADER_NOT_AVAILABLE}
[ERROR] [2016-06-28 23:54:01.618] [akka.actor.ActorSystemImpl] This server does not host this topic-partition.
org.apache.kafka.common.errors.UnknownTopicOrPartitionException: This server does not host this topic-partition.
[INFO] [2016-06-28 23:54:01.619] [akka.actor.ActorSystemImpl] Producing: test-10
[ERROR] [2016-06-28 23:54:01.619] [akka.actor.ActorSystemImpl] This server does not host this topic-partition.
org.apache.kafka.common.errors.UnknownTopicOrPartitionException: This server does not host this topic-partition.
[ERROR] [2016-06-28 23:54:01.619] [akka.actor.ActorSystemImpl] This server does not host this topic-partition.
org.apache.kafka.common.errors.UnknownTopicOrPartitionException: This server does not host this topic-partition.
[ERROR] [2016-06-28 23:54:01.620] [akka.actor.ActorSystemImpl] This server does not host this topic-partition.
org.apache.kafka.common.errors.UnknownTopicOrPartitionException: This server does not host this topic-partition.
[ERROR] [2016-06-28 23:54:01.620] [akka.actor.ActorSystemImpl] This server does not host this topic-partition.
org.apache.kafka.common.errors.UnknownTopicOrPartitionException: This server does not host this topic-partition.
[ERROR] [2016-06-28 23:54:01.624] [akka.actor.ActorSystemImpl] This server does not host this topic-partition.
org.apache.kafka.common.errors.UnknownTopicOrPartitionException: This server does not host this topic-partition.
[WARN] [2016-06-28 23:54:01.637] [o.apache.kafka.clients.NetworkClient] Error while fetching metadata with correlation id 9 : {test=LEADER_NOT_AVAILABLE}
[INFO] [2016-06-28 23:54:02.357] [akka.actor.ActorSystemImpl] Producing: test-11
[INFO] [2016-06-28 23:54:02.369] [akka.actor.ActorSystemImpl] Produced message: test-11, topic test, partition: null, offset: 33
[INFO] [2016-06-28 23:54:03.357] [akka.actor.ActorSystemImpl] Producing: test-12
[INFO] [2016-06-28 23:54:03.359] [akka.actor.ActorSystemImpl] Produced message: test-12, topic test, partition: null, offset: 34
[INFO] [2016-06-28 23:54:04.356] [akka.actor.ActorSystemImpl] Producing: test-13
[INFO] [2016-06-28 23:54:04.358] [akka.actor.ActorSystemImpl] Produced message: test-13, topic test, partition: null, offset: 35
[INFO] [2016-06-28 23:54:05.358] [akka.actor.ActorSystemImpl] Producing: test-14
[INFO] [2016-06-28 23:54:05.360] [akka.actor.ActorSystemImpl] Produced message: test-14, topic test, partition: null, offset: 36
[INFO] [2016-06-28 23:54:06.356] [akka.actor.ActorSystemImpl] Producing: test-15
[INFO] [2016-06-28 23:54:06.358] [akka.actor.ActorSystemImpl] Produced message: test-15, topic test, partition: null, offset: 37
```

Is this the expected behavior? Or should the fetch metadata failures be handled more gracefully by reactive-kafka?

**Comment by iravid** [comment]
If you need a workaround, you can get the underlying client to handle this with retries by setting the `retries` property on the producer settings.

Note that this can cause reordering of messages, so you'll also need to set `max.in.flight.requests.per.connection` to 1 to avoid that.

**Comment by bfil** [comment]
The workaround seem to work fine, sometimes though I get the following exception, and the producer just dies:

```
[ERROR] [2016-06-29 10:36:15.195] [akka.actor.RepointableActorRef] Error in stage [akka.kafka.internal.ProducerStage@7d42af6e]: Memory records is not writable
java.lang.IllegalStateException: Memory records is not writable
	at org.apache.kafka.common.record.MemoryRecords.append(MemoryRecords.java:93)
	at org.apache.kafka.clients.producer.internals.RecordBatch.tryAppend(RecordBatch.java:69)
	at org.apache.kafka.clients.producer.internals.RecordAccumulator.append(RecordAccumulator.java:168)
	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:435)
	at akka.kafka.internal.ProducerStage$$anon$1$$anon$3.onPush(ProducerStage.scala:66)
	at akka.stream.impl.fusing.GraphInterpreter.processElement$1(GraphInterpreter.scala:587)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:598)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:539)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:472)
	at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:424)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:604)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:619)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:482)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:530)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by iravid** [comment]
Yup. That's a known bug in the 0.9 version of Kafka that was fixed in 0.10: https://issues.apache.org/jira/browse/KAFKA-3147

Mentioned this in #160.

**Comment by bfil** [comment]
Oh, I've read the issue but missed the comment about `IllegalStateExceptions` completely, well, that's annoying.. Thanks btw @iravid

**Comment by 13h3r** [comment]
@bfil in your example you set decider to `Resume`. So, in case of error akka stream just drop this message and process next one. In my opinion current behavior is correct. What do you think?

**Comment by bfil** [comment]
@13h3r The retries setting does the trick, and failures can be handled manually if needed, so I guess this can be closed.
