### ISSUE TITLE
requirement failed message in 0.11-M4

### ISSUE THREAD

**Issue by xelax** [akka/reactive-kafka#189]
While running 0.11-M4 I've got this error:

2016-08-10 10:10:50,056 ERROR a.a.OneForOneStrategy - requirement failed
java.lang.IllegalArgumentException: requirement failed
	at scala.Predef$.require(Predef.scala:212)
	at akka.kafka.KafkaConsumerActor.poll(KafkaConsumerActor.scala:182)
	at akka.kafka.KafkaConsumerActor$$anonfun$receive$1.applyOrElse(KafkaConsumerActor.scala:101)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
	at akka.kafka.KafkaConsumerActor.aroundReceive(KafkaConsumerActor.scala:56)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by kciesielski** [comment]
Can you reproduce this error somehow? It is caused by internal `.poll()` call returning different messages for different partitions than expected. It would be good to have a failing test for this.

**Comment by xelax** [comment]
I got it when I had 3 different instances of a listener on the same queue and then I kill one of them, and I see the error in the console of the other one. I will try to see whether I can trigger this reliably.

**Comment by kciesielski** [comment]
Thanks, @xelax 

@13h3r I suspect that consumer assignment changed before `poll()`  (https://github.com/akka/reactive-kafka/blob/master/core/src/main/scala/akka/kafka/KafkaConsumerActor.scala#L167) hence poll returned more than expected, WDYT?

**Comment by xelax** [comment]
Yes, it sounds likely to me, besides my listeners are getting updates in large batches with few thousands of largish messages in them, so it is quite possible that while getting the messages the consumer assignment get changed.

**Comment by 13h3r** [comment]
@xelax did you use auto or manual partition assignment assignment?

@kciesielski How assignment may be changed before poll? And how it may broke the code?

**Comment by 13h3r** [comment]
Please try build from master. Looks like https://github.com/akka/reactive-kafka/pull/179 fixes this

**Comment by kciesielski** [comment]
@13h3r It can be changed by rebalance, but as you pointed to #179 I can see now that pause will be called, so it should be properly handled.

**Comment by 13h3r** [comment]
Could you check it? //@xelax

**Comment by xelax** [comment]
sorry, was out on vacation last week. I will build and try it out today or tomorrow.
thanks!

**Comment by xelax** [comment]
I tried it out with the new build and the problem seems to be solved.
