### ISSUE TITLE
improve error handling for WakeupTimeoutException

### ISSUE THREAD

**Issue by patriknw** [akka/reactive-kafka#224]
When I introduced the wakup in https://github.com/akka/reactive-kafka/pull/220 I was thinking that ordinary actor supervision would be enough, but based on feedback in the gitter channel the logging of the exception is causing confusion.

We should implement some error handling for this in the actor itself instead. Then we can have a shorter timeout to let the actor be responsive for other things, but still retry a number of times before finally stopping, and thereby terminating the stream(s).

**Comment by patriknw** [comment]
Let's do this after the 0.11 release. I'll increase the timeout for now to 10 seconds.

**Comment by nemccarthy** [comment]
Hey @patriknw, not sure what was the error report in the gitter chat, but I'm seeing behaviour that sounds familiar from the description;

Start consumer, connects fine and as expected see a subscription is made;
```
16/09/12 18:52:28 INFO utils.AppInfoParser: Kafka version : 0.10.0.1
16/09/12 18:52:28 INFO utils.AppInfoParser: Kafka commitId : a7a17cdec9eaa6c5
16/09/12 18:52:28 INFO internals.AbstractCoordinator: Discovered coordinator 192.168.99.100:32768 (id: 2147482646 rack: null) for group g_segmentActivator.
16/09/12 18:52:28 INFO internals.ConsumerCoordinator: Revoking previously assigned partitions [] for group g_segmentActivator
16/09/12 18:52:28 INFO internals.AbstractCoordinator: (Re-)joining group g_segmentActivator
16/09/12 18:52:28 INFO internals.AbstractCoordinator: Successfully joined group g_segmentActivator with generation 1
16/09/12 18:52:28 INFO internals.ConsumerCoordinator: Setting newly assigned partitions [t_segments1-0] for group g_segmentActivator
```

If I then restart the consumer, it will pause until the timeout is triggered. From going through the message flow it looks like the subscription is never recreated so the system just sits there doing nothing... 

I've tried upping the timeout from 5s to 15s and I still have the same problems. 

Is there a workaround aside from large timeouts?

Logs:
```
16/09/12 18:48:22 INFO consumer.ConsumerConfig: ConsumerConfig values: 
	metric.reporters = []
	metadata.max.age.ms = 300000
	partition.assignment.strategy = [org.apache.kafka.clients.consumer.RangeAssignor]
	reconnect.backoff.ms = 50
	sasl.kerberos.ticket.renew.window.factor = 0.8
	max.partition.fetch.bytes = 1048576
	bootstrap.servers = [192.168.99.100:32768]
	ssl.keystore.type = JKS
	enable.auto.commit = false
	sasl.mechanism = GSSAPI
	interceptor.classes = null
	exclude.internal.topics = true
	ssl.truststore.password = null
	client.id = 
	ssl.endpoint.identification.algorithm = null
	max.poll.records = 2147483647
	check.crcs = true
	request.timeout.ms = 40000
	heartbeat.interval.ms = 3000
	auto.commit.interval.ms = 5000
	receive.buffer.bytes = 65536
	ssl.truststore.type = JKS
	ssl.truststore.location = null
	ssl.keystore.password = null
	fetch.min.bytes = 1
	send.buffer.bytes = 131072
	value.deserializer = class au.com.quantium.qdmp.util.AvroSpecificKafkaDeserializer
	group.id = g_segmentActivator
	retry.backoff.ms = 100
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	sasl.kerberos.service.name = null
	sasl.kerberos.ticket.renew.jitter = 0.05
	ssl.trustmanager.algorithm = PKIX
	ssl.key.password = null
	fetch.max.wait.ms = 500
	sasl.kerberos.min.time.before.relogin = 60000
	connections.max.idle.ms = 540000
	session.timeout.ms = 30000
	metrics.num.samples = 2
	key.deserializer = class org.apache.kafka.common.serialization.ByteArrayDeserializer
	ssl.protocol = TLS
	ssl.provider = null
	ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
	ssl.keystore.location = null
	ssl.cipher.suites = null
	security.protocol = PLAINTEXT
	ssl.keymanager.algorithm = SunX509
	metrics.sample.window.ms = 30000
	auto.offset.reset = earliest

16/09/12 18:48:23 INFO consumer.ConsumerConfig: ConsumerConfig values: 
	metric.reporters = []
	metadata.max.age.ms = 300000
	partition.assignment.strategy = [org.apache.kafka.clients.consumer.RangeAssignor]
	reconnect.backoff.ms = 50
	sasl.kerberos.ticket.renew.window.factor = 0.8
	max.partition.fetch.bytes = 1048576
	bootstrap.servers = [192.168.99.100:32768]
	ssl.keystore.type = JKS
	enable.auto.commit = false
	sasl.mechanism = GSSAPI
	interceptor.classes = null
	exclude.internal.topics = true
	ssl.truststore.password = null
	client.id = consumer-1
	ssl.endpoint.identification.algorithm = null
	max.poll.records = 2147483647
	check.crcs = true
	request.timeout.ms = 40000
	heartbeat.interval.ms = 3000
	auto.commit.interval.ms = 5000
	receive.buffer.bytes = 65536
	ssl.truststore.type = JKS
	ssl.truststore.location = null
	ssl.keystore.password = null
	fetch.min.bytes = 1
	send.buffer.bytes = 131072
	value.deserializer = class au.com.quantium.qdmp.util.AvroSpecificKafkaDeserializer
	group.id = g_segmentActivator
	retry.backoff.ms = 100
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	sasl.kerberos.service.name = null
	sasl.kerberos.ticket.renew.jitter = 0.05
	ssl.trustmanager.algorithm = PKIX
	ssl.key.password = null
	fetch.max.wait.ms = 500
	sasl.kerberos.min.time.before.relogin = 60000
	connections.max.idle.ms = 540000
	session.timeout.ms = 30000
	metrics.num.samples = 2
	key.deserializer = class org.apache.kafka.common.serialization.ByteArrayDeserializer
	ssl.protocol = TLS
	ssl.provider = null
	ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
	ssl.keystore.location = null
	ssl.cipher.suites = null
	security.protocol = PLAINTEXT
	ssl.keymanager.algorithm = SunX509
	metrics.sample.window.ms = 30000
	auto.offset.reset = earliest

16/09/12 18:48:23 INFO utils.AppInfoParser: Kafka version : 0.10.0.1
16/09/12 18:48:23 INFO utils.AppInfoParser: Kafka commitId : a7a17cdec9eaa6c5
16/09/12 18:48:23 INFO internals.AbstractCoordinator: Discovered coordinator 192.168.99.100:32768 (id: 2147482646 rack: null) for group g_segmentActivator.
16/09/12 18:48:24 INFO internals.ConsumerCoordinator: Revoking previously assigned partitions [] for group g_segmentActivator
16/09/12 18:48:24 INFO internals.AbstractCoordinator: (Re-)joining group g_segmentActivator
[ERROR] [09/12/2016 18:48:39.919] [default-akka.actor.default-dispatcher-5] [akka://default/system/kafka-consumer-1] null
org.apache.kafka.common.errors.WakeupException
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.maybeTriggerWakeup(ConsumerNetworkClient.java:367)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.clientPoll(ConsumerNetworkClient.java:361)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:224)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:192)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:163)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureActiveGroup(AbstractCoordinator.java:243)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.ensurePartitionAssignment(ConsumerCoordinator.java:366)
	at org.apache.kafka.clients.consumer.KafkaConsumer.pollOnce(KafkaConsumer.java:978)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:938)
	at akka.kafka.KafkaConsumerActor.poll(KafkaConsumerActor.scala:193)
	at akka.kafka.KafkaConsumerActor$$anonfun$receive$1.applyOrElse(KafkaConsumerActor.scala:113)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
	at akka.kafka.KafkaConsumerActor.aroundReceive(KafkaConsumerActor.scala:66)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

16/09/12 18:48:45 INFO consumer.ConsumerConfig: ConsumerConfig values: 
	metric.reporters = []
	metadata.max.age.ms = 300000
	partition.assignment.strategy = [org.apache.kafka.clients.consumer.RangeAssignor]
	reconnect.backoff.ms = 50
	sasl.kerberos.ticket.renew.window.factor = 0.8
	max.partition.fetch.bytes = 1048576
	bootstrap.servers = [192.168.99.100:32768]
	ssl.keystore.type = JKS
	enable.auto.commit = false
	sasl.mechanism = GSSAPI
	interceptor.classes = null
	exclude.internal.topics = true
	ssl.truststore.password = null
	client.id = 
	ssl.endpoint.identification.algorithm = null
	max.poll.records = 2147483647
	check.crcs = true
	request.timeout.ms = 40000
	heartbeat.interval.ms = 3000
	auto.commit.interval.ms = 5000
	receive.buffer.bytes = 65536
	ssl.truststore.type = JKS
	ssl.truststore.location = null
	ssl.keystore.password = null
	fetch.min.bytes = 1
	send.buffer.bytes = 131072
	value.deserializer = class au.com.quantium.qdmp.util.AvroSpecificKafkaDeserializer
	group.id = g_segmentActivator
	retry.backoff.ms = 100
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	sasl.kerberos.service.name = null
	sasl.kerberos.ticket.renew.jitter = 0.05
	ssl.trustmanager.algorithm = PKIX
	ssl.key.password = null
	fetch.max.wait.ms = 500
	sasl.kerberos.min.time.before.relogin = 60000
	connections.max.idle.ms = 540000
	session.timeout.ms = 30000
	metrics.num.samples = 2
	key.deserializer = class org.apache.kafka.common.serialization.ByteArrayDeserializer
	ssl.protocol = TLS
	ssl.provider = null
	ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
	ssl.keystore.location = null
	ssl.cipher.suites = null
	security.protocol = PLAINTEXT
	ssl.keymanager.algorithm = SunX509
	metrics.sample.window.ms = 30000
	auto.offset.reset = earliest

16/09/12 18:48:45 INFO consumer.ConsumerConfig: ConsumerConfig values: 
	metric.reporters = []
	metadata.max.age.ms = 300000
	partition.assignment.strategy = [org.apache.kafka.clients.consumer.RangeAssignor]
	reconnect.backoff.ms = 50
	sasl.kerberos.ticket.renew.window.factor = 0.8
	max.partition.fetch.bytes = 1048576
	bootstrap.servers = [192.168.99.100:32768]
	ssl.keystore.type = JKS
	enable.auto.commit = false
	sasl.mechanism = GSSAPI
	interceptor.classes = null
	exclude.internal.topics = true
	ssl.truststore.password = null
	client.id = consumer-2
	ssl.endpoint.identification.algorithm = null
	max.poll.records = 2147483647
	check.crcs = true
	request.timeout.ms = 40000
	heartbeat.interval.ms = 3000
	auto.commit.interval.ms = 5000
	receive.buffer.bytes = 65536
	ssl.truststore.type = JKS
	ssl.truststore.location = null
	ssl.keystore.password = null
	fetch.min.bytes = 1
	send.buffer.bytes = 131072
	value.deserializer = class au.com.quantium.qdmp.util.AvroSpecificKafkaDeserializer
	group.id = g_segmentActivator
	retry.backoff.ms = 100
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	sasl.kerberos.service.name = null
	sasl.kerberos.ticket.renew.jitter = 0.05
	ssl.trustmanager.algorithm = PKIX
	ssl.key.password = null
	fetch.max.wait.ms = 500
	sasl.kerberos.min.time.before.relogin = 60000
	connections.max.idle.ms = 540000
	session.timeout.ms = 30000
	metrics.num.samples = 2
	key.deserializer = class org.apache.kafka.common.serialization.ByteArrayDeserializer
	ssl.protocol = TLS
	ssl.provider = null
	ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
	ssl.keystore.location = null
	ssl.cipher.suites = null
	security.protocol = PLAINTEXT
	ssl.keymanager.algorithm = SunX509
	metrics.sample.window.ms = 30000
	auto.offset.reset = earliest

16/09/12 18:48:45 INFO utils.AppInfoParser: Kafka version : 0.10.0.1
16/09/12 18:48:45 INFO utils.AppInfoParser: Kafka commitId : a7a17cdec9eaa6c5
16/09/12 18:48:45 INFO internals.AbstractCoordinator: Discovered coordinator 192.168.99.100:32768 (id: 2147482646 rack: null) for group g_segmentActivator.

```

**Comment by jvwilge** [comment]
I'm not sure if this helps, but I also got the Exception after some restarts shortly after each other while fiddling around. This piece of code (adapted from http://stackoverflow.com/questions/33481156/how-to-stop-gracefully-the-actor-system-for-an-akka-http-server-that-must-be-dep) fixed it for me. The Exception can of course still appear on non-graceful shutdowns, but this will fix the quick restarts.

`// prevent WakeupException on quick restarts of vm
    scala.sys.addShutdownHook {
      println("Terminating... - " + Instant.now)
      system.terminate()
      Await.result(system.whenTerminated, 30 seconds)
      println("Terminated... Bye - " + Instant.now)
    }`

**Comment by nemccarthy** [comment]
Thanks @jvwilge! that seems to have solved it for quick restarts. Now its just occasional (running kafka in a docker locally for testing) and sometimes its a bit slow to respond so upping the timeout is the only real workaround I've found. 

Is there something I'm missing that the stream doesn't resume on wakeup exception because the subscriptions are never resent (I'm new to the streams side of akka, just want to make sure I'm not doing something stupid).

**Comment by kciesielski** [comment]
Any kind of exception would now cause consumer actor to restart. The actor creates a new consumer but this consumer never receives topic subscription. We need to re-send subscriptions (or fail the stage for `AssignmentWithOffset`).
