### ISSUE TITLE
AskTimeoutException when using commitScaladsl

### ISSUE THREAD

**Issue by YunLiaw** [akka/reactive-kafka#266]
Hello,

I sometimes receive this error when running reactive kafka and I do not have any clue.

```
akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka://default/system/kafka-consumer-1#1749876186]] after [15000 ms]. Sender[null] sent message of type "akka.kafka.KafkaConsumerActor$Internal$Commit".
	at akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:604)
	at akka.actor.Scheduler$$anon$4.run(Scheduler.scala:126)
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:601)
	at scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:109)
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:599)
	at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(LightArrayRevolverScheduler.scala:329)
	at akka.actor.LightArrayRevolverScheduler$$anon$4.executeBucket$1(LightArrayRevolverScheduler.scala:280)
	at akka.actor.LightArrayRevolverScheduler$$anon$4.nextTick(LightArrayRevolverScheduler.scala:284)
	at akka.actor.LightArrayRevolverScheduler$$anon$4.run(LightArrayRevolverScheduler.scala:236)
	at java.lang.Thread.run(Thread.java:745)
```

And below is the code for the stream:

```scala
    Consumer.committablePartitionedSource(consumerSettings, Subscriptions.topics("consumerTopic"))
    .map { case (_, source) =>
      source
      .map { m =>
        
        // business logic
        toProducerMessage(...)
      }
      .via(Producer.flow(producerSettings, producerSettings.createKafkaProducer()))
      .map(_.message.passThrough)
      .batch(20, CommittableOffsetBatch.empty.updated) { (batch, elem) => batch.updated(elem) }
      .mapAsync(producerSettings.parallelism)(_.commitScaladsl()) // I believe here's the place for the exception
      .toMat(Sink.ignore)(Keep.right)
      .run()
    }
    .mapAsyncUnordered(consumerMaxPartition)(identity)
    .to(Sink.ignore)
  }.run()
```

This exception will sometimes happen. For now I have two ways to avoid this exception:
1. Add retry on commitScaladsl. It will introduce dead letter warning
```
INFO  [2017-01-19 16:34:05,847] akka.actor.DeadLetterActorRef: Message [akka.kafka.KafkaConsumerActor$Internal$Committed] from Actor[akka://default/system/kafka-consumer-1#929979950] to Actor[akka://default/deadLetters] was not delivered. [7] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
```
2. Use `Supervision.Resume` supervision strategy to ignore this exception

For now I prefer to use first method to deal with the AskTimeoutException. But I don't know if there is any potential problem with this?

Regards,
Yun

**Comment by kciesielski** [comment]
Hi Yun. This looks like internal committer actor is not responding for some reason. If retry results in dead letters, then it looks like this actor is dead. Even ignoring your commit with `Resume` would then result in dead letters in resuts. Or do you see further commits passing?

**Comment by YunLiaw** [comment]
I have to correct that what I have tried is using `Supervision.Restart` rather than `Supervision.Resume`. With `Supervision.Restart` or retry I can see the stream will keep processing messages and the offset will keep changing. 

Is there any way to investigate the reason that cause internal commiter actor not responding?

**Comment by yoeluk** [comment]
This is broken in the same way for me too

**Comment by patriknw** [comment]
I agree, this is important to investigate. Can't promise I will be able to do it this week, but it's on my radar.

**Comment by shadius** [comment]
Hi, I am able to reproduce this issue as well, my code:

`      consumerStream = Some(rawEventsConsumer
        .to(createEventFlow()
            .via(PreWhalModelStage(modelEndpoint, modelApi))
            .via(WhalModelStage(sendToModel, metrics))
            .via(PostWhalModelStage(system))
            .map(sm =>
              ProducerMessage.Message(
                new ProducerRecord[String, String](
                  outTopic,
                  sm.stateMessage.metadata().gtpId(),
                  om.writeValueAsString(sm.stateMessage)),
                sm.committable)
            )
            .to(Producer.commitableSink(producerSettings))).run())`

**Comment by krchniam** [comment]
Hi, we also encountered this issue couple of months ago. When doing my initial investigation I found out that these timeouts correlate with Kafka rebalansing due to expired ZooKeeper session (we have only one Kafka broker). We bumped `akka.kafka.consumer.commit-timeout` to 20s, then to 30s but to no avail. Now we are running with `commit-timeout = 60s`. It looks like Kafka is not responding for almost 50s, but offset is eventually commited:
```
2017-02-07 09:44:40,785 ERROR Processing failed: offset = 218665, key = Some(58998814930000bf21f25521)
akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka://kafka-reader/system/kafka-consumer-3#1185779635]] after [30000 ms]. Sender[null] sent message of type "akka.kafka.KafkaConsumerActor$Internal$Commit".
	at akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:604)
	at akka.actor.Scheduler$$anon$4.run(Scheduler.scala:126)
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:601)
	at scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:109)
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:599)
	at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(LightArrayRevolverScheduler.scala:331)
	at akka.actor.LightArrayRevolverScheduler$$anon$4.executeBucket$1(LightArrayRevolverScheduler.scala:282)
	at akka.actor.LightArrayRevolverScheduler$$anon$4.nextTick(LightArrayRevolverScheduler.scala:286)
	at akka.actor.LightArrayRevolverScheduler$$anon$4.run(LightArrayRevolverScheduler.scala:238)
	at java.lang.Thread.run(Unknown Source)
2017-02-07 09:45:00,473 INFO  Message [akka.kafka.KafkaConsumerActor$Internal$Committed] from Actor[akka://kafka-reader/system/kafka-consumer-3#1185779635] to Actor[akka://kafka-reader/deadLetters] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
```

 Can you check if it is your case? I will be doing thorough investigation of our logs in the next couple of days/weeks to check if all these timeouts correlate with Kafka rebalansing.

**Comment by gabriele83** [comment]
+1

**Comment by vlovgr** [comment]
Any progress on this one?

**Comment by mwz** [comment]
+1

**Comment by patriknw** [comment]
I have tried a few things to understand what happens when client/consumer loose connection with the broker.

Stopping broker, waiting a few seconds before restarting, triggering a WakeupException, then it works fine.

Quick restart of broker:
```
org.apache.kafka.clients.consumer.RetriableCommitFailedException: Offset commit failed with a retriable exception. You should retry committing offsets. The underlying error was: This is not the correct coordinator.
```

`kill -9` of broker and then start after a few seconds:
```
org.apache.kafka.clients.consumer.RetriableCommitFailedException: Offset commit failed with a retriable exception. You should retry committing offsets. The underlying error was: null
```

One thing to note is that when broker is stopped the `consumer.poll` will block, until the wakeup is triggered, which by default is `3 s`. If you have increased the wakeup-timeout > commit-timeout (default 15 s) then there will be an AskTimeout if this blocking occurs.

**Comment by mohnishkodnani** [comment]
we are also seeing this error in our application

**Comment by ennru** [comment]
Let's try and get more information on the scenarios where committing times out. Please report the version of the Alpakka Kafka connector/Reactive Kafka and the version of the Kafka cluster.
Does it happen all the time or in certain scenarios? 
The underlying implementation uses `KafkaConsumer.commitAsync`, but the Kafka Consumer Actor might be stuck in something else so that the Commit message doesn't even get handled.

**Comment by mohnishkodnani** [comment]
For me 
akka-stream-kafka -> 0.13
Kafka Cluster : 0.10.0.0
The problem does not happen all the time. I am yet to pinpoint what condition triggers this. 
i have a log statement before the commit stage, that gets printed definitely a 1 minute ago, and then the ask timeout happens at 60000ms. 
Unfortunately, i cannot use the later/latest versions to see if there is something in the older version.

**Comment by mohnishkodnani** [comment]
The pattern in the logs seems to be
1. Wakeup Exception
2. Committing offsets {}
3. Pausing partition

and then repeat 1,2,3 
Then after a point only 1,3 until say the commit timeout set and then AskTimeout

**Comment by ennru** [comment]
@mohnishkodnani The situation with the AskTimeException during commit from 0.13 has been vastly improved. I hope you will be able to upgrade Kafka and the Alpakka Kafka connector soon.

**Comment by dmi3zkm** [comment]
@ennru 
Kafka version - 1.1
alpakka-kafka - 0.22
using autocommit

**Comment by ennru** [comment]
Do you have problems with timeouts on committing while using autocommit?

**Comment by mohnishkodnani** [comment]
I didnt try auto commit, since from the get go, i had to control the commit
to kafka after i persist the message and not when i receive.

**Comment by dmi3zkm** [comment]
@ennru 
> Do you have problems with timeouts on committing while using autocommit?
Sometimes I get error messages saying that:
1. "[Consumer clientId=ConsumerX, groupId=GroupX] Offset commit failed on partition TopicX-1 at offset N: The request timed out.".
2. "[Consumer clientId=ConsumerY, groupId=GroupY] Offset commit failed on partition TopicY-1 at offset N: The coordinator is not aware of this member."   
And sometimes consumer stops consuming at all. Interesting things is that stream doesn't complete (I have a health check asking consumer control whether stream is alive or not), but consumer lag grows until I restart the consumer. And one more detail is that it started after updating `0.16` to `0.22` I'm trying to reproduce the situation. I will keep you informed.

**Comment by dmi3zkm** [comment]
Many thanks. 
I'll keep investigating.

**Comment by kciesielski** [comment]
We are getting similar errors:
```
Offset commit failed on partition xxx-yyy-32 at offset 642258: The request timed out.
```
from `org.apache.kafka.clients.consumer.internals.ConsumerCoordinator` which causes our stream to restart. Happens on production (sometimes once a day, sometimes few times a day), we couldn't replicate this on test environments. It looks like some internal Kafka problem with broker failing to get commit confirmations from other Kafka nodes. We can catch this particular error rethrown by Reactive Kafka for now.

However, I just wanted to point out that this happens on Kafka 2.0.0. Maybe an upgrade to 2.1.0 would help, but first we'd need Reactive Kafka to reach final release.

**Comment by ennru** [comment]
Interesting findings @kciesielski 
I'd like to encourage you to try with a 1.0-RC version, we consider them as viable as the earlier 0.x versions.

**Comment by Ashfakh** [comment]
I'm facing the same issue for my Akka consumer in production as well

[Consumer clientId=consumer-3, groupId=xxx] Offset commit failed on partition topicX at offset y: The request timed out.

Does it have anything to do with the number of consumer threads and partitions?
After this error, the consumer stops consuming at all. Any help would be much appreciated.

**Comment by jonbuffington** [comment]
@ennru I can confirm this issue persists in 1.0-RC2.

```
ERROR: o.a.k.c.c.i.ConsumerCoordinator: [Consumer clientId=consumer-1, groupId=XXX] Offset commit failed on partition XXX-1 at offset 634761238: The request timed out.
WARN : a.k.i.KafkaConsumerActor: Kafka commit took longer than `commit-time-warning`: 5043 ms
a.a.ActorSystemImpl: Offset commit failed with a retriable exception. You should retry committing the latest consumed offsets.
org.apache.kafka.clients.consumer.RetriableCommitFailedException: Offset commit failed with a retriable exception. You should retry committing the latest consumed offsets.
Caused by: org.apache.kafka.common.errors.TimeoutException: The request timed out.
```

**Comment by ennru** [comment]
Thank you for trying the latest milestones out so eagerly.
We haven't changed anything in this area, so it could be expected to still see this failure.
It would be great if you can provide a bit more information around when this happens and what settings you use. To fix this we would want to trigger the failure consistently.
I assume it should be possible to retry the commit when Kafka reports a `RetriableCommitFailedException`...

**Comment by gaxhaje** [comment]
I am currently seeing the following dead letters message which is killing the stream but without any exceptions. The stream just dies silently. 

```
INFO  2020-02-26 22:02:37,944 [StreamingIngestion-akka.actor.default-dispatcher-17] akka.actor.DeadLetterActorRef [akka://StreamingIngestion/deadLetters] - Message [akka.kafka.internal.KafkaConsumerActor$Internal$Committed] from Actor[akka://StreamingIngestion/system/kafka-consumer-14#1695552649] to Actor[akka://StreamingIngestion/deadLetters] was not delivered. [1] dead letters encountered. If this is not an expected behavior, then [Actor[akka://StreamingIngestion/deadLetters]] may have terminated unexpectedly, This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
```

I have a client that is on Kafka 1.1.0 and thought it to be related to the below issue because streams go hours without processing any messages. I have tried different settings for the `commit-refresh-interval` but now think that this is not the issue because not all the active streams die. Note that each stream has it's own Kafka consumer. I have thought about using a shared consumer for all streams as they are all listening to the same Kafka cluster but then the issue above would most likely kill all of them.

```
# If set to a finite duration, the consumer will re-send the last committed offsets periodically
# for all assigned partitions. See https://issues.apache.org/jira/browse/KAFKA-4682.
commit-refresh-interval = 4h
```

I would like to implement a workaround with `Supervision.Restart` strategy as @YunLiaw has but how can I go about implementing that without an exception being through into my supervision strategy? I do not get an `AskTimeoutException` or any exceptions related to the consumer.

Dependencies:
`scala 2.12`

`akka-actor-2.5.21`

`akka-stream-2.5.21`

`akka-stream-kafka-1.0.RC2`

`kafka-clients-1.0.0`


```
# Properties for akka.kafka.ConsumerSettings can be
# defined in this section or a configuration section with
# the same layout.
akka.kafka.consumer {
  # Tuning property of scheduled polls.
  # Controls the interval from one scheduled poll to the next.
  poll-interval = 100ms
 
  # Tuning property of the `KafkaConsumer.poll` parameter.
  # Note that non-zero value means that the thread that
  # is executing the stage will be blocked. See also the `wakup-timeout` setting below.
  poll-timeout = 100ms
 
  # The stage will delay stopping the internal actor to allow processing of
  # messages already in the stream (required for successful committing).
  # Prefer use of `DrainingControl` over a large stop-timeout.
  stop-timeout = 30s
 
  # Duration to wait for `KafkaConsumer.close` to finish.
  close-timeout = 20s
 
  # If offset commit requests are not completed within this timeout
  # the returned Future is completed `CommitTimeoutException`.
  commit-timeout = 15s
 
  # If commits take longer than this time a warning is logged
  commit-time-warning = 1s
 
  # Not used anymore (since 1.0-RC1)
  # wakeup-timeout = 3s
 
  # Not used anymore (since 1.0-RC1)
  # max-wakeups = 10
 
  # If set to a finite duration, the consumer will re-send the last committed offsets periodically
  # for all assigned partitions. See https://issues.apache.org/jira/browse/KAFKA-4682.
  commit-refresh-interval = 4h
 
  # Not used anymore (since 1.0-RC1)
  # wakeup-debug = true
 
  # Fully qualified config path which holds the dispatcher configuration
  # to be used by the KafkaConsumerActor. Some blocking may occur.
  use-dispatcher = "akka.kafka.default-dispatcher"
 
  # Properties defined by org.apache.kafka.clients.consumer.ConsumerConfig
  # can be defined in this configuration section.
  kafka-clients {
    # Disable auto-commit by default
    enable.auto.commit = false
  }
 
  # Time to wait for pending requests when a partition is closed
  wait-close-partition = 500ms
 
  # Limits the query to Kafka for a topic's position
  position-timeout = 5s
 
  # When using `AssignmentOffsetsForTimes` subscriptions: timeout for the
  # call to Kafka's API
  offset-for-times-timeout = 5s
 
  # Timeout for akka.kafka.Metadata requests
  # This value is used instead of Kafka's default from `default.api.timeout.ms`
  # which is 1 minute.
  metadata-request-timeout = 5s
}
```

**Comment by seglo** [comment]
> I am currently seeing the following dead letters message which is killing the stream but without any exceptions. The stream just dies silently.
> 
> ```
> INFO  2020-02-26 22:02:37,944 [StreamingIngestion-akka.actor.default-dispatcher-17] akka.actor.DeadLetterActorRef [akka://StreamingIngestion/deadLetters] - Message [akka.kafka.internal.KafkaConsumerActor$Internal$Committed] from Actor[akka://StreamingIngestion/system/kafka-consumer-14#1695552649] to Actor[akka://StreamingIngestion/deadLetters] was not delivered. [1] dead letters encountered. If this is not an expected behavior, then [Actor[akka://StreamingIngestion/deadLetters]] may have terminated unexpectedly, This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
> ```

I think your stream is dead before this logline.  This is indicating an offset commit took was requested, but never reached its destination (the `KafkaConsumerActor`).  This usually happens when a late commit request is sent after the stream shuts down.

You don't see any other exceptions taking place?  Do you have logging enabled for the `akka.kafka` namespace?

**Comment by ennru** [comment]
I'd suggest to upgrade to a more recent version of Alpakka Kafka. We've improved in that area.

**Comment by omeraha** [comment]
@ennru Agreed, but even in the latest version the `TimeoutException` is not being handled (AFAIU)

**Comment by ennru** [comment]
Thanks for sending #1584! I'll have a look next week.

**Comment by omeraha** [comment]
@ennru, thanks. While you're at it, it might be worth considering a fix for a broader set of cases, as I've seen additional retriable exceptions popping up in our logs (`CoordinatorLoadInProgressException`, for instance). Since these errors all extend the `RetriableException` exception, it might be a better idea to cover the more general case. If you agree, you can make a comment on the [PR](https://github.com/akka/alpakka-kafka/pull/1584) and I'll fix it
