### ISSUE TITLE
ConsumerTest failing on windows

### ISSUE THREAD

**Issue by mmatloka** [akka/reactive-kafka#276]
`"call commitAsync for every commit message (no commit batching)"` fails with
```Ask timed out on [Actor[akka://default/system/kafka-consumer-13#-19172456]] after [1000 ms]. Sender[null] sent message of type "akka.kafka.KafkaConsumerActor$Internal$Commit".
akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka://default/system/kafka-consumer-13#-19172456]] after [1000 ms]. Sender[null] sent message of type "akka.kafka.KafkaConsumerActor$Internal$Commit".
    at akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:604)
    at akka.actor.Scheduler$$anon$4.run(Scheduler.scala:126)
    at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:601)
    at scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:109)
    at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:599)
    at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(LightArrayRevolverScheduler.scala:329)
    at akka.actor.LightArrayRevolverScheduler$$anon$4.executeBucket$1(LightArrayRevolverScheduler.scala:280)
    at akka.actor.LightArrayRevolverScheduler$$anon$4.nextTick(LightArrayRevolverScheduler.scala:284)
    at akka.actor.LightArrayRevolverScheduler$$anon$4.run(LightArrayRevolverScheduler.scala:236)
    at java.lang.Thread.run(Thread.java:745)```

**Comment by asluk** [comment]
Raising the commitTimeout in the testSource's ConsumerSettings from 1.second to 2.seconds at https://github.com/akka/reactive-kafka/blob/master/core/src/test/scala/akka/kafka/internal/ConsumerTest.scala#L89 seemed to address this for me in my Windows setup. But I'm not sure what's specific to Windows that could make this block more contentious; the 1.second timeout is sufficient when running the test on Ubuntu over virtualbox on the same Windows machine.

**Comment by 2m** [comment]
Closing this ticket due to inactivity. Please re-open this ticket with more information if you still find the original issue relevant.

Recently we added quite a few integration tests using embedded kafka. It would be possible to run these tests in CI using Appveyor. If anyone is interested in adding appveyor setup for that, feel free to open a PR.
