### ISSUE TITLE
Akka Stream Kafka - Avro Desereilization

### ISSUE THREAD

**Issue by yarshad** [akka/reactive-kafka#342]
Hi,
Using Kafka Source in Akka Streams Kafka, I am trying to deserialize an Avro object using KafkaAvroDeserializer that is created using avro-tools library.

If I use confluent Kafka Consumer, I can deserialize it like this:

def consumerProperties() = {
  val props = new Properties
  props.put("bootstrap.servers", kafkaServer)
  props.put("group.id", UUID.randomUUID().toString)
  props.put("auto.commit.enable", "false")
  props.put("auto.offset.reset", "earliest")
  props.put("schema.registry.url", schemaUrl)
  props.put(KafkaAvroDeserializerConfig.SPECIFIC_AVRO_READER_CONFIG, "true")
  props.put("key.deserializer", "org.apache.kafka.common.serialization.StringDeserializer")
  props.put("value.deserializer", "io.confluent.kafka.serializers.KafkaAvroDeserializer")
  props
}

def consume(): Unit ={

  val consumer = new KafkaConsumer[String, Person](consumerProperties)
 consumer.subscribe(Collections.singletonList(topic))

  while(true){
    val records : ConsumerRecords[String, Person] =consumer.poll(100)
    records.forEach(i => println(i.value().getName))
}
}

But I am unable to deserialize using Kafka source in Akka Streams Kafka.
The consumer settings is of type ConsumerSettings[String, AnyRef], and I think I need to somehow change it to ConsumerSettings[String, Person]

val consumerSettings  = ConsumerSettings(system,new StringDeserializer, new KafkaAvroDeserializer)
  .withBootstrapServers(kafkaServer)
  .withGroupId(UUID.randomUUID().toString)
  .withProperty(ConsumerConfig.AUTO_OFFSET_RESET_CONFIG, "earliest")
  .withProperty("schema.registry.url", schemaUrl)
  .withProperty(KafkaAvroDeserializerConfig.SPECIFIC_AVRO_READER_CONFIG, "true")
  .withProperty("key.deserializer", "org.apache.kafka.common.serialization.StringDeserializer")
  .withProperty("value.deserializer", "io.confluent.kafka.serializers.KafkaAvroDeserializer")

val  subscriptions = Subscriptions.topics(topic)
val output  = Consumer.plainSource(consumerSettings,subscriptions)
output

**Comment by patriknw** [comment]
There is a type parameter for the value. Have you tried `ConsumerSettings[String, Person](system,new StringDeserializer, new KafkaAvroDeserializer)` ?

**Comment by ChenShuai1981** [comment]
Did the issue mentioned be fixed? I met the same issue when tried reactive kafka with confluent schema registry, is there any official guide for the integration?

**Comment by lilyevsky** [comment]
It is not completely broken, there is an easy workaround. The only problem with Akka Streams Kafka is that the registry URL property does not automatically get into the deserializer from ConsumerSettings. So we have to configure the deserializer ourselves, something like this:
```
import scala.collection.JavaConverters._

  val kafkaAvroDeserializerConfig = Map[String, Any] {
    AbstractKafkaAvroSerDeConfig.SCHEMA_REGISTRY_URL_CONFIG -> config.schemaRegistryUrl
  }
  val kafkaAvroDeserializer = new KafkaAvroDeserializer
  kafkaAvroDeserializer.configure(kafkaAvroDeserializerConfig.asJava, false)

  val consumerSettings = ConsumerSettings(system, new StringDeserializer,
    kafkaAvroDeserializer.asInstanceOf[Deserializer[GenericRecord]])
    .withBootstrapServers(config.bootstrapServers)
    .withGroupId(config.groupId)
    .withClientId(config.clientId)
    .withPollInterval(config.pollTimeoutMs milliseconds)
    .withProperty(ConsumerConfig.AUTO_OFFSET_RESET_CONFIG, "latest")
    .withProperty(ConsumerConfig.ENABLE_AUTO_COMMIT_CONFIG, "false")
```
I actually tested this, it works (was stuck for about half a day)

**Comment by Camsteack** [comment]
It would be nice to have that for Java

**Comment by niqdev** [comment]
With the following basic config for the Producer
```scala
val producerSettings = ProducerSettings(actorSystem, new StringSerializer, new KafkaAvroSerializer)
      .withBootstrapServers(kafkaConfig.servers)
      .withProperty(AbstractKafkaAvroSerDeConfig.SCHEMA_REGISTRY_URL_CONFIG, kafkaConfig.schemaRegistry)
```
I had this error
```
13:24:44.297 [WARN] o.a.k.c.p.ProducerConfig - The configuration 'schema.registry.url' was supplied but isn't a known config.
13:24:44.702 [ERROR] a.a.RepointableActorRef - Error in stage [akka.kafka.internal.ProducerStage$DefaultProducerStage@7b418515]: Error serializing Avro message
org.apache.kafka.common.errors.SerializationException: Error serializing Avro message
Caused by: java.lang.NullPointerException: null
	at io.confluent.kafka.serializers.AbstractKafkaAvroSerializer.serializeImpl(AbstractKafkaAvroSerializer.java:82)
	at io.confluent.kafka.serializers.KafkaAvroSerializer.serialize(KafkaAvroSerializer.java:53)
	at org.apache.kafka.common.serialization.ExtendedSerializer$Wrapper.serialize(ExtendedSerializer.java:65)
	at org.apache.kafka.common.serialization.ExtendedSerializer$Wrapper.serialize(ExtendedSerializer.java:55)
	at org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:783)
```
but thanks to @lilyevsky for his workaround, I solve it in a similar way
```scala
import akka.actor.ActorSystem
import akka.kafka.ProducerSettings
import io.confluent.kafka.serializers.{AbstractKafkaAvroSerDeConfig, KafkaAvroSerializer}
import org.apache.kafka.common.serialization.StringSerializer

final class KafkaSettings(actorSystem: ActorSystem) {
  private[this] lazy val kafkaConfig = AppSettings(actorSystem).Kafka

  /*
   * @see https://github.com/akka/alpakka-kafka/issues/342
   */
  private[this] def newKafkaAvroSerializer(isKey: Boolean = false): KafkaAvroSerializer = {
    import scala.collection.JavaConverters.mapAsJavaMapConverter

    val configMap = Map(AbstractKafkaAvroSerDeConfig.SCHEMA_REGISTRY_URL_CONFIG -> kafkaConfig.schemaRegistry)

    val kafkaAvroSerializer = new KafkaAvroSerializer
    kafkaAvroSerializer.configure(configMap.asJava, isKey)
    kafkaAvroSerializer
  }

  /*
   * @see https://docs.confluent.io/current/schema-registry/docs/serializer-formatter.html#serializer
   */
  val producerSettings: ProducerSettings[String, AnyRef] =
    ProducerSettings(actorSystem, new StringSerializer, newKafkaAvroSerializer())
      .withBootstrapServers(kafkaConfig.servers)
}

object KafkaSettings {
  def apply()(implicit actorSystem: ActorSystem): KafkaSettings =
    new KafkaSettings(actorSystem)
}
```
For completeness, since I couldn't find any simple working example, I've used [avro4s](https://github.com/sksamuel/avro4s#conversions-tofrom-genericrecord) in this way
```scala
case class Example(key: String, value: String)
val example = Example("myKey", "myValue")
val format = RecordFormat[Example]
val value = format.to(example)
val record = new ProducerRecord[String, AnyRef]("events", example.key, value)
ProducerMessage.Message(record, example)
```

**Comment by ChenShuai1981** [comment]
How can I get a "SpecificRecord" instead of "GenericRecord" shown in @lilyevsky example code?

**Comment by viktor-pecheniuk** [comment]
> It is not completely broken, there is an easy workaround. The only problem with Akka Streams Kafka is that the registry URL property does not automatically get into the deserializer from ConsumerSettings. So we have to configure the deserializer ourselves, something like this:
> 
> ```
> import scala.collection.JavaConverters._
> 
>   val kafkaAvroDeserializerConfig = Map[String, Any] {
>     AbstractKafkaAvroSerDeConfig.SCHEMA_REGISTRY_URL_CONFIG -> config.schemaRegistryUrl
>   }
>   val kafkaAvroDeserializer = new KafkaAvroDeserializer
>   kafkaAvroDeserializer.configure(kafkaAvroDeserializerConfig.asJava, false)
> 
>   val consumerSettings = ConsumerSettings(system, new StringDeserializer,
>     kafkaAvroDeserializer.asInstanceOf[Deserializer[GenericRecord]])
>     .withBootstrapServers(config.bootstrapServers)
>     .withGroupId(config.groupId)
>     .withClientId(config.clientId)
>     .withPollInterval(config.pollTimeoutMs milliseconds)
>     .withProperty(ConsumerConfig.AUTO_OFFSET_RESET_CONFIG, "latest")
>     .withProperty(ConsumerConfig.ENABLE_AUTO_COMMIT_CONFIG, "false")
> ```
> 
> I actually tested this, it works (was stuck for about half a day)

Thank you @lilyevsky , works well :)
