### ISSUE TITLE
Unable to consume events using assignmentOffsetsForTimes

### ISSUE THREAD

**Issue by Fraer** [akka/reactive-kafka#485]
I would like to fetch events that were produced during the last 24 hours, ie consume events after a specific timestamp:

```scala
val partitions: Seq[TopicPartition] = consumerSettings
    .createKafkaConsumer()
    .partitionsFor(kafka.topic)
    .asScala
    .map { t => new TopicPartition(kafka.topic, t.partition()) }

val lastDate: Long = System.currentTimeMillis() - (1000 * 60 * 60 * 24)
val topicsAndDate = Subscriptions.assignmentOffsetsForTimes(partitions.map(_ -> lastDate): _*)
Consumer
    .plainSource[Array[Byte], String](consumerSettings, topicsAndDate)
    .map(_.value())
    ....
```

But i'm getting the following errors:
```
(nio-consent-events-0,null) (of class scala.Tuple2)
scala.MatchError: (nio-consent-events-0,null) (of class scala.Tuple2)
        at akka.kafka.KafkaConsumerActor$$anonfun$receive$1.$anonfun$applyOrElse$3(KafkaConsumerActor.scala:126)
        at akka.kafka.KafkaConsumerActor$$anonfun$receive$1.$anonfun$applyOrElse$3$adapted(KafkaConsumerActor.scala:126)
        at scala.collection.Iterator.foreach(Iterator.scala:929)
        at scala.collection.Iterator.foreach$(Iterator.scala:929)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
        at scala.collection.IterableLike.foreach(IterableLike.scala:71)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at akka.kafka.KafkaConsumerActor$$anonfun$receive$1.applyOrElse(KafkaConsumerActor.scala:126)
        at akka.actor.Actor.aroundReceive(Actor.scala:517)
        at akka.actor.Actor.aroundReceive$(Actor.scala:515)
        at akka.kafka.KafkaConsumerActor.aroundReceive(KafkaConsumerActor.scala:85)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
        at akka.actor.ActorCell.invoke(ActorCell.scala:496)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)

Exception when polling from consumer
java.lang.IllegalStateException: Consumer is not subscribed to any topics or assigned any partitions
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1109)
        at akka.kafka.KafkaConsumerActor.tryPoll$1(KafkaConsumerActor.scala:298)
        at akka.kafka.KafkaConsumerActor.poll(KafkaConsumerActor.scala:360)
        at akka.kafka.KafkaConsumerActor$$anonfun$receive$1.applyOrElse(KafkaConsumerActor.scala:181)
        at akka.actor.Actor.aroundReceive(Actor.scala:517)
        at akka.actor.Actor.aroundReceive$(Actor.scala:515)
        at akka.kafka.KafkaConsumerActor.aroundReceive(KafkaConsumerActor.scala:85)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
        at akka.actor.ActorCell.invoke(ActorCell.scala:496)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
```

broker version: kafka_2.12-1.0.0
client version: akka-stream-kafka 0.20

**Comment by 2m** [comment]
What is the version of reactive-kafka that you are using?

**Comment by Fraer** [comment]
Sorry, i forgot to specify the version of akka-stream-kafka, i've updated the issue. I was using version 0.20 of akka-stream-kafka.

**Comment by 2m** [comment]
It could be a bug in the connector. Let me get back to you a bit later after some investigation.

**Comment by 2m** [comment]
From the exception it looks like `null` is returned as an offset for that particular topic. From the [Kafka API docs](https://kafka.apache.org/11/javadoc/org/apache/kafka/clients/consumer/KafkaConsumer.html#offsetsForTimes-java.util.Map-):

>  If the message format version in a partition is before 0.10.0, i.e. the messages do not have timestamps, null will be returned for that partition.

Do you know if the message format of your topic is before 0.10.0?

**Comment by Fraer** [comment]
Don't think so. I'm running a local kafka server v1.1.0 and akka-stream-kafka v0.20 is using kafka-clients-1.0.1.jar
And no older clients produced records in this topic.

**Comment by Fraer** [comment]
Looks like this error occurs when the topic exists and is empty.
But for unknown reason it occurs also when the topic exists and is not empty, probably when there were no records produced during the last 24h.

**Comment by 2m** [comment]
Thanks for the pointers. It looks like under those conditions `null` is also returned which is not handled properly.
