### ISSUE TITLE
Locale is not handled properly

### ISSUE THREAD

**Issue by tanjucat** [akka/reactive-kafka#96]
When trying the Scala example in the Readme, we run into an error on some machines. The error message is below. It turned out that if the JVM local language is Turkish, which has different upper case for the lower case letter `i`, the result is a runtime error caused by `org.apache.kafka.clients.consumer.OffsetResetStrategy`. More specifically an `enum` constant `EARLİEST` is generated which does not match `EARLIEST` (note the dotted capital i).

If the locale for the JVM is explicitly set to `en_US`, the example runs as expected.

The full error is below:

```
[ERROR] [02/26/2016 17:35:33.244] [ReactiveKafka-akka.actor.default-dispatcher-3] [akka://ReactiveKafka/user/$a] Failed to construct kafka consumer
akka.actor.ActorInitializationException: exception during creation
at akka.actor.ActorInitializationException$.apply(Actor.scala:172)
at akka.actor.ActorCell.create(ActorCell.scala:606)
at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:461)
at akka.actor.ActorCell.systemInvoke(ActorCell.scala:483)
at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
at akka.dispatch.Mailbox.run(Mailbox.scala:223)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:648)
at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:542)
at com.softwaremill.react.kafka.ReactiveKafkaConsumer.consumer$lzycompute(ReactiveKafkaConsumer.scala:31)
at com.softwaremill.react.kafka.ReactiveKafkaConsumer.consumer(ReactiveKafkaConsumer.scala:30)
at com.softwaremill.react.kafka.KafkaActorPublisher.<init>(KafkaActorPublisher.scala:17)
at com.softwaremill.react.kafka.ReactiveKafka$$anonfun$consumerActorProps$1.apply(ReactiveKafka.scala:270)
at com.softwaremill.react.kafka.ReactiveKafka$$anonfun$consumerActorProps$1.apply(ReactiveKafka.scala:270)
at akka.actor.TypedCreatorFunctionConsumer.produce(IndirectActorProducer.scala:87)
at akka.actor.Props.newActor(Props.scala:214)
at akka.actor.ActorCell.newActor(ActorCell.scala:562)
at akka.actor.ActorCell.create(ActorCell.scala:588)
... 7 more
Caused by: java.lang.IllegalArgumentException: No enum constant org.apache.kafka.clients.consumer.OffsetResetStrategy.EARLİEST
at java.lang.Enum.valueOf(Enum.java:238)
at org.apache.kafka.clients.consumer.OffsetResetStrategy.valueOf(OffsetResetStrategy.java:15)
at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:588)
... 17 more
```

**Comment by kciesielski** [comment]
@tanjucat We allow passing any string-string pair to settings, apparently Kafka client does some uppercasing and enum generation for some cases. I don't think we are going to handle this in our library, this looks like an issue to be reported in [`kafka-clients`](https://issues.apache.org/jira/browse/KAFKA/component/12315218/?selectedTab=com.atlassian.jira.jira-projects-plugin:component-issues-panel).

**Comment by tanjucat** [comment]
Thanks @kciesielski . I just reported the issue in `kafka-clients`.
